<?xml version='1.0'?>

<robot name="diff_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="box_chassis" params="length width height mass">

  <link name='chassis'>

    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <!-- Color For Rviz-->
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${mass}"/>
      <origin xyz="${length/4} 0 0" rpy=" 0 0 0"/>
      <xacro:box_inertia m="${mass}" x="${length}" y="${width}" z="${height}" xd="${length/4}"/>
    </inertial>

  </link>

  <joint name="chassis_joint" type="fixed">
    <origin xyz="${-length/4} 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="chassis" />
  </joint>

</xacro:macro>

</robot>